language: haskell

deploy:
  provider: hackage
  username: thriqon
  password:
    secure: HNARFehGwnJ1FfTAuM3ZL6YeecQP3HDtZn1udLma4S4oi/dTOiuqtOLhvU5Vc2rGFUmg5xe8gKXYoemChe8pK1/QU5zpa11o+3K91PgL9WewmRDvkmcrTPICA6Hq6UXfJ+MKdf5umSnQ+SPYaKPjnDODghfuGC+tp0Z1v9KTBeAVlJxxE8EX/eHOO+3wwDDRmAOkx0m1DN2JvUi/fdL7wOMbFISQ0WsK+y+ppWa8vMNCdY+Wm0ZcjjpDUiOXHE+NvnacIMjQEYCCe520BFyvrL5iDuDQ+gwkwI2tPyHnx1NaMVDAdA64+wPmD/b7It/7qt4ZxXsvAofWplPGxXk712XI8Y89rNhGDWrd3f9eV0Lldk9hVLg1cxXAqQhkSQSX252JSsKu20SUmyEHfGyFLrer7DQxk7yGg+YxsnBEJSy3I2ZnlsJxyyYslTunxUctGoq19x9h1SfRguKd5oWyi1Ug55imAJSC+vEraVcAU5DNrxnT+gqJnNW/3TM92MfP7a8lDWIbK9YPGP0vVR0V6t6QsS+04aukKCsMIuLdfsiEkFHjbCL1zMehUftj3WmA527SP/9ZWkS70AvS6qvzQJ6/Vg8UxaMSG6wiPIXGoopL5SM5UTxEBRu4trm145oTnXF0gLjfzQ3SKn9Hh/MTQWPofpsmCeJeUHMtchaOepQ=
  on:
    repo: thriqon/pandoc-plantuml-diagrams
    tags: true
