name:                pandoc-plantuml-diagrams
version:             0.1.0.4
github:              thriqon/pandoc-plantuml-diagrams
synopsis:            Render and insert PlantUML diagrams with Pandoc
description:         PlantUML renders different types of UML diagrams.
                     This filter invokes plantuml.jar (which must be present
                     in the current directory) for any yet unrendered diagrams.
                     .
                     Diagrams are recognized in CodeBlocks that have the
                     class "uml". It is advisable to also include an attribute
                     "caption", which is rendered as alternate text for the image.
                     If an ID is present, it is additionally appended compatible
                     with pandoc-crossref.
license:             MIT
license-file:        LICENSE
author:              Jonas Weber
maintainer:          "contact@jonasw.de"
category:            Text
cabal-version:       ">=1.10"
extra-source-files:
- README.md

dependencies:
- base               >= 4 && < 5
- pandoc-types
- SHA
- process
- directory
- utf8-string
- bytestring
# - hspec
# - QuickCheck

library:
  source-dirs:       src

executables:
  pandoc-plantuml-diagrams:
    main:              Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-plantuml-diagrams

tests:
  test-pandoc-crossref:
    main:            Spec.hs
    source-dirs:     test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-discover
    - mtl
    - pandoc-plantuml-diagrams
